In [1]:
import numpy as np
import numpy.linalg as linalg
import matplotlib.pyplot as plt

In [2]:
X = np.array([[27, 35, 40, 38,  2,  3, 48, 29, 46, 31],
              [32, 39, 21, 36, 19, 42, 49, 26, 22, 13],
              [41, 17, 45, 24, 23,  4, 33, 14, 30, 10],
              [28, 44, 34, 18, 20, 25,  6,  7, 47,  1],
              [16,  0, 15,  5, 11,  9,  8, 12, 43, 37]], dtype=np.float)
m, n = X.shape

In [3]:
mX = np.mean(X, axis = 0) 
A = X - mX
r = np.linalg.matrix_rank(A)
r

4

In [4]:
#1 AtA

AtA = np.dot(A.T, A)
ata_w, V = linalg.eigh(AtA) # AtA is symmetric
# decending order by reverse
ata_w = ata_w[::-1] 
V = V[:, ::-1]
AtA.shape, ata_w.shape, V.shape

((10, 10), (10,), (10, 10))

In [5]:
# 10개로 계산
np.round(ata_w, 2)

array([3600.43, 2144.32, 1316.3 ,  878.14,    0.  ,    0.  ,    0.  ,
         -0.  ,   -0.  ,   -0.  ])

In [6]:
np.round(V[:, :r], 2)

array([[-0.19,  0.06,  0.24, -0.35],
       [-0.46,  0.34,  0.14,  0.57],
       [-0.15, -0.06,  0.64, -0.07],
       [-0.43, -0.16,  0.05,  0.11],
       [-0.03,  0.27,  0.04, -0.38],
       [-0.26,  0.46, -0.57,  0.04],
       [-0.59, -0.47, -0.11, -0.17],
       [-0.22, -0.26, -0.14,  0.1 ],
       [ 0.2 , -0.03,  0.24,  0.55],
       [ 0.21, -0.53, -0.29,  0.21]])

In [7]:
#2 AAt
mX = np.mean(X, axis = 0) 
A = X - mX
AAt = np.dot(A, A.T)

aat_w, U = linalg.eigh(AAt) # AAt is symmetric
# decending order by reverse
aat_w = aat_w[::-1] 
U = U[:, ::-1]
AtA.shape, aat_w.shape, U.shape

((10, 10), (5,), (5, 5))

In [8]:
# 5개로 계산
np.round(aat_w, 2)

array([3600.43, 2144.32, 1316.3 ,  878.14,   -0.  ])

In [9]:
V2 = np.dot(A.T, U) 
V2 = V2 / np.linalg.norm(V2, axis=0).reshape(1, -1)# unit vector
np.round(V2[:, :r], 2)

array([[-0.19, -0.06, -0.24, -0.35],
       [-0.46, -0.34, -0.14,  0.57],
       [-0.15,  0.06, -0.64, -0.07],
       [-0.43,  0.16, -0.05,  0.11],
       [-0.03, -0.27, -0.04, -0.38],
       [-0.26, -0.46,  0.57,  0.04],
       [-0.59,  0.47,  0.11, -0.17],
       [-0.22,  0.26,  0.14,  0.1 ],
       [ 0.2 ,  0.03, -0.24,  0.55],
       [ 0.21,  0.53,  0.29,  0.21]])

In [10]:
# Eigenvector sign matching
for k  in range(r): # r = 4
    if V[0,k]*V2[0, k]< 0:   # the first element sign in V, V2
        V2[:,k] = -V2[:,k]

In [11]:
np.round(V2[:, :r], 2)

array([[-0.19,  0.06,  0.24, -0.35],
       [-0.46,  0.34,  0.14,  0.57],
       [-0.15, -0.06,  0.64, -0.07],
       [-0.43, -0.16,  0.05,  0.11],
       [-0.03,  0.27,  0.04, -0.38],
       [-0.26,  0.46, -0.57,  0.04],
       [-0.59, -0.47, -0.11, -0.17],
       [-0.22, -0.26, -0.14,  0.1 ],
       [ 0.2 , -0.03,  0.24,  0.55],
       [ 0.21, -0.53, -0.29,  0.21]])

In [12]:
np.allclose(V[:,:r], V2[:,:r])

True