In [3]:
import numpy as np
import numpy.linalg as linalg
import matplotlib.pyplot as plt

In [4]:
# 2D coordinates (x, y) in columns
X = np.array([[0,  0,  0, 100, 100, 150,-100,-150],
              [0, 50,-50,   0,  30, 100, -20,-100]], dtype=np.float32)

m, n = X.shape

In [7]:
mX = np.mean(X, axis = 1)
mX =  mX.reshape(-1, 1) #mX[:, np.newaxis]
mX

array([[12.5 ],
       [ 1.25]], dtype=float32)

In [8]:
A = X - mX 
C = np.dot(A, A.T)
#C = np.dot(A, A.T)/(n-1) # sample covariance, np.cov(X, ddof=1)
C

array([[73750. , 34875. ],
       [34875. , 26287.5]], dtype=float32)

In [9]:
w, V = linalg.eigh(C) # C is symmetric
# decending order by reverse
w = w[::-1] 
V = V[:, ::-1]
V
print(C.shape, w.shape, V.shape)

(2, 2) (2,) (2, 2)


In [6]:
# PCA projection
A = X - mX
Y = np.dot(V.T, A )
np.round(Y,2)

array([[  11.63,  -11.75,   35.02,  -76.76,  -90.79, -167.72,  109.38,
         190.99],
       [  -4.74,  -48.94,   39.45,   42.03,   15.51,  -22.98,  -33.83,
          13.5 ]])

In [7]:
# PCA back projection
X2 = np.dot(V, Y) + mX
np.round(X2)

array([[   0.,   -0.,    0.,  100.,  100.,  150., -100., -150.],
       [  -0.,   50.,  -50.,    0.,   30.,  100.,  -20., -100.]])

In [8]:
np.allclose(X2, X)

True

In [9]:
# Approximation using back projection with k-PC
k = 1
Vk = V.copy()
Vk[:, k:] = 0
Xk = np.dot(Vk, Y) + mX
np.round(Xk)

array([[   2.,   23.,  -18.,   80.,   93.,  161.,  -84., -156.],
       [  -4.,    7.,  -15.,   37.,   44.,   80.,  -50.,  -88.]])

In [10]:
error = np.sqrt(np.sum((X - Xk)**2)) # Frobenius Norm
error

88.51760505419699