### 7.2 허프, 직선 검출

In [1]:
import cv2
import numpy as np

src = cv2.imread('c:/data/rect.jpg')
gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
edges = cv2.Canny(gray, 50, 100)
lines = cv2.HoughLines(edges, 1, np.pi/180, 100)

for line in lines:
    r, t = line[0]
    c = np.cos(t)
    s = np.sin(t)
    x0 = c * r
    y0 = s * r
    x1 = int(x0 + 1000 * (-s))
    y1 = int(y0 + 1000 * c)
    x2 = int(x0 - 1000 * (-s))
    y2 = int(y0 - 1000 * c)
    cv2.line(src, (x1, y1), (x2, y2), (0, 0, 255), 2)

cv2.imshow('edges', edges)
cv2.imshow('src', src)
cv2.waitKey()
cv2.destroyAllWindows()

### 7.3 선분 검출

In [5]:
import cv2
import numpy as np

src = cv2.imread('c:/data/rect.jpg')
gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
edges = cv2.Canny(gray, 50, 100)
lines = cv2.HoughLinesP(edges, 1, np.pi/180, 100)

for line in lines:
    x1, y1, x2, y2 = line[0]
    cv2.line(src, (x1, y1), (x2, y2), (0, 0, 255), 2)

cv2.imshow('edges', edges)
cv2.imshow('src', src)
cv2.waitKey()
cv2.destroyAllWindows()

### 7.4 원 검출

In [1]:
import cv2
import numpy as np

src1 = cv2.imread('c:/data/circles.jpg')
gray1 = cv2.cvtColor(src1, cv2.COLOR_BGR2GRAY)
circles1 = cv2.HoughCircles(gray1, cv2.HOUGH_GRADIENT, 1, 50, param2=15)

circles1 = np.int32(circles1)
print(circles1.shape)
for circle in circles1[0,:]:
    cx, cy, r = circle
    cv2.circle(src1, (cx, cy), r, (0, 0, 255), 2)
cv2.imshow('src1', src1)

src2 = cv2.imread('c:/data/circles2.jpg')
gray2 = cv2.cvtColor(src2, cv2.COLOR_BGR2GRAY)
circles2 = cv2.HoughCircles(gray2, cv2.HOUGH_GRADIENT, 1, 50, param2=15, minRadius=30, maxRadius=100)

circles2 = np.int32(circles2)
print(circles2.shape)
for circle in circles2[0, :]:
    cx, cy, r = circle
    cv2.circle(src2, (cx, cy), r, (0, 0, 255), 2)
cv2.imshow('src2', src2)
cv2.waitKey()
cv2.destroyAllWindows()

(1, 3, 3)
(1, 6, 3)


### 7.6 윤곽선 검출

In [13]:
import cv2
import numpy as np

src = np.zeros(shape=(512, 512, 3), dtype=np.uint8)
cv2.rectangle(src, (50, 100), (450, 400), (255, 255, 255), -1)
cv2.rectangle(src, (100, 150), (400, 350), (0, 0, 0), -1)
cv2.rectangle(src, (200, 200), (300, 300), (255, 255, 255), -1)
gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)

mode = cv2.RETR_EXTERNAL
method = cv2.CHAIN_APPROX_SIMPLE # 꼭지점만 검출
# method = cv2.CHAIN_APPROX_SIMPLE # 모든 부분 검출

# 윤곽선 검출
contours, hierarchy = cv2.findContours(gray, mode, method)
print(type(contours))
print(type(contours[0]))
print(len(contours))
print(contours[0].shape)
print(contours[0])

# 윤곽선 그리기
cv2.drawContours(src, contours, -1, (255, 0, 0), 3)

# 윤곽선 좌표 그리기
for pt in contours[0][:]:
    cv2.circle(src, (pt[0][0], pt[0][1]), 5, (0, 0 ,255), -1)

cv2.imshow('src', src)
cv2.waitKey()
cv2.destroyAllWindows()

<class 'tuple'>
<class 'numpy.ndarray'>
1
(4, 1, 2)
[[[ 50 100]]

 [[ 50 400]]

 [[450 400]]

 [[450 100]]]


### 7.7 모든 윤곽선 검출

In [2]:
import cv2
import numpy as np

# 8.1 예제 사진으로 실행 할 경우
# src = cv2.imread('c:/data/CornerTest.jpg')
# gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)

src = np.zeros(shape=(512, 512, 3), dtype=np.uint8)
cv2.rectangle(src, (50, 100), (450, 400), (255, 255, 255), -1)
cv2.rectangle(src, (100, 150), (400, 350), (0, 0, 0), -1)
cv2.rectangle(src, (200, 200), (300, 300), (255, 255, 255), -1)
gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)

mode = cv2.RETR_LIST
method = cv2.CHAIN_APPROX_SIMPLE # 꼭지점만 검출
# method = cv2.CHAIN_APPROX_NONE # 모든 부분 검출

# 윤곽선 검출
contours, hierarchy = cv2.findContours(gray, mode, method)
print(type(contours))
print(type(contours[0]))
print(len(contours))
print(contours[0].shape)
print(contours[0])

# 윤곽선 그리기
for cnt in contours:
    cv2.drawContours(src, [cnt], -1, (255, 0, 0), 3)

    # 꼭지점 좌표 그리기
    for pt in cnt:
        cv2.circle(src, (pt[0][0], pt[0][1]), 5, (0, 0 ,255), -1)

cv2.imshow('src', src)
cv2.waitKey()
cv2.destroyAllWindows()

<class 'tuple'>
<class 'numpy.ndarray'>
3
(4, 1, 2)
[[[200 200]]

 [[200 300]]

 [[300 300]]

 [[300 200]]]


### 7.11 영상 분할, 물체 찾기

In [20]:
import cv2
import numpy as np

src = cv2.imread('c:/data/circles2.jpg')
gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
ret, bImage = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY_INV+cv2.THRESH_OTSU)

dist = cv2.distanceTransform(bImage, cv2.DIST_L1, 3)
dist8 = cv2.normalize(dist, None, 0, 255, cv2.NORM_MINMAX, dtype=cv2.CV_8U)

cv2.imshow('bImage', bImage)
cv2.imshow('dist8', dist8)

minV, maxV, minL, maxL = cv2.minMaxLoc(dist)
print(minV, maxV, minL, maxL)
mask = (dist>maxV*0.5).astype(np.uint8)*255
cv2.imshow('mask', mask)

mode = cv2.RETR_EXTERNAL
method = cv2.CHAIN_APPROX_SIMPLE
contours, hierarchy = cv2.findContours(mask, mode, method)
print(len(contours)) # 물체 검출

markers = np.zeros(shape=src.shape[:2], dtype=np.int32)
for i, cnt in enumerate(contours):
    cv2.drawContours(markers, [cnt], 0, i+1, -1)

dst = src.copy()
cv2.watershed(src, markers)

dst[markers==-1] == [0, 0, 255]
for i in range(len(contours)):
    r = np.random.randint(256)
    g = np.random.randint(256)
    b = np.random.randint(256)
    dst[markers==i+1] = [b, g, r]
dst = cv2.addWeighted(src, 0.4, dst, 0.6, 0)

cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()


0.0 76.0 (0, 0) (220, 220)
6


### kmeans 클러스터링

In [4]:
import cv2
import numpy as np

src = cv2.imread('c:/data/hand.jpg')
hsv = cv2.cvtColor(src, cv2.COLOR_BGR2HSV)

data = src.reshape((-1, 3)).astype(np.float32)

K = 2
term_crit = (cv2.TERM_CRITERIA_MAX_ITER+cv2.TERM_CRITERIA_EPS, 10, 1.0)
ret, labels, centers = cv2.kmeans(data, K, None, term_crit, 5, cv2.KMEANS_RANDOM_CENTERS)
print(centers.shape)
print(labels.shape)
print(ret)

centers = np.uint8(centers)
res = centers[labels.flatten()]
dst = res.reshape(src.shape)
cv2.imshow('dst', dst)

#hsv를 이용하는 경우
labels2 = np.uint8(labels.reshape(src.shape[:2]))
print(labels2.max())
dst2 = np.zeros(src.shape, dtype=src.dtype)
for i in range(K):
    r = np.random.randint(256)
    g = np.random.randint(256)
    b = np.random.randint(256)
    dst2[labels2==i] = [b, g, r]
cv2.imshow('dst2', dst2)

cv2.waitKey()
cv2.destroyAllWindows()

(2, 3)
(230400, 1)
62989280.689894974
1


### 7.15 레이블링을 이용한 물체 찾기

In [9]:
import cv2
import numpy as np

src = cv2.imread('c:/data/circles.jpg')
gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
# circle을 물체로 인식하고 싶은 경우
ret, res = cv2.threshold(gray, 128, 255, cv2.THRESH_BINARY_INV)

# 배경을 물체로 인식하고 싶은 경우
# ret, res = cv2.threshold(gray, 128, 255, cv2.THRESH_BINARY)

ret, labels = cv2.connectedComponents(res)
print(ret) # 물체의 개수, 배경 포함

dst = np.zeros(src.shape, dtype=src.dtype)
for i in range(1, ret):
    r = np.random.randint(256)
    g = np.random.randint(256)
    b = np.random.randint(256)
    dst[labels == i] = [b, g, r]

cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()

4


### 7.16 레이블링을 이용한 물체 인식, 객체 정보도 반환

In [3]:
import cv2
import numpy as np

src = cv2.imread('c:/data/circles.jpg')
gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
ret, res = cv2.threshold(gray, 128, 255, cv2.THRESH_BINARY_INV)

ret, labels, stats, centroids = cv2.connectedComponentsWithStats(res)
print(ret) # 객체의 수, 배경 포함
print(stats) # 시작좌표 (x, y), width, height, 픽셀 개수
print(centroids) # 각 객체의 중심점 좌표 (x, y)

dst = np.zeros(src.shape, dtype=src.dtype)
for i in range(1, int(ret)):
    r = np.random.randint(256)
    g = np.random.randint(256)
    b = np.random.randint(256)
    dst[labels==i] = [b, g, r]

for i in range(1, int(ret)):
    x, y, width, height, area = stats[i]
    cv2.rectangle(dst, (x, y), (x+width, y+height), (0, 0, 255), 2)
    
    cx, cy = centroids[i]
    cv2.circle(dst, (int(cx), int(cy)), 5, (255, 0, 0), -1)

cv2.imshow('src', src)
cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()

4
[[     0      0    512    512 222719]
 [   308     86    125    125  12281]
 [   153    145    152    152  18152]
 [   292    338    107    107   8992]]
[[247.77339607 258.80937863]
 [370.         148.        ]
 [228.5        220.50534376]
 [345.00077847 390.99477313]]
