### 4.23 마하라노비스 통계적 거리

In [2]:
import cv2
import numpy as np

X = np.array([[0, 0, 0, 100, 100, 150, -100, -150],
              [0, 50, -50, 0, 30, 100, -20, -100]], dtype=np.float64)

X = X.T

cov, mean = cv2.calcCovarMatrix(X, None, cv2.COVAR_NORMAL+cv2.COVAR_ROWS)
print(mean, cov)

ret, icov = cv2.invert(cov)

v1 = np.array([[0], [0]], dtype=np.float64)
v2 = np.array([[0], [50]], dtype=np.float64)

dst = cv2.Mahalanobis(v1, v2, icov)
print(dst)

[[12.5   1.25]] [[73750.  34875. ]
 [34875.  26287.5]]
0.5051854992128457


### 4.25 PCA 투영, 역투영

In [15]:
import cv2
import numpy as np

X = np.array([[0, 0, 0, 100, 100, 150, -100, -150],
              [0, 50, -50, 0, 30, 100, -20, -100]], dtype=np.float64)
X = X.T
print(X)
mean, eVects = cv2.PCACompute(X, None)

Y = cv2.PCAProject(X, mean, eVects)
print(Y)

X2 = cv2.PCABackProject(Y, mean, eVects)
print(np.round(X2))

print(np.allclose(X, X2))

K = 1
vk = eVects.copy()
vk[K:, :] = 0
xk = cv2.PCABackProject(Y, mean, eVects)
# xk = xk.T
error = np.sqrt(np.sum((X-xk)**2))
print(np.round(error))

[[   0.    0.]
 [   0.   50.]
 [   0.  -50.]
 [ 100.    0.]
 [ 100.   30.]
 [ 150.  100.]
 [-100.  -20.]
 [-150. -100.]]
[[ -11.63338792    4.74096885]
 [  11.75000868   48.93618085]
 [ -35.01678451  -39.45424315]
 [  76.75703609  -42.02582434]
 [  90.78707404  -15.50869713]
 [ 167.71904127   22.98120308]
 [-109.37717055   33.82967723]
 [-190.9858171   -13.49926538]]
[[   0.    0.]
 [   0.   50.]
 [   0.  -50.]
 [ 100.   -0.]
 [ 100.   30.]
 [ 150.  100.]
 [-100.  -20.]
 [-150. -100.]]
True
156.49395891409313
