In [1]:
import numpy as np
import numpy.linalg as linalg
import matplotlib.pyplot as plt

In [2]:
# 4 vectors with 10-dimension
# each row is a vector

#np.random.seed(1)
#X = np.arange(50)
#np.random.shuffle(X)
#X = X.reshape(-1, 10)
#X
X = np.array([[27, 35, 40, 38,  2,  3, 48, 29, 46, 31],
              [32, 39, 21, 36, 19, 42, 49, 26, 22, 13],
              [41, 17, 45, 24, 23,  4, 33, 14, 30, 10],
              [28, 44, 34, 18, 20, 25,  6,  7, 47,  1],
              [16,  0, 15,  5, 11,  9,  8, 12, 43, 37]], dtype=np.float)
m, n = X.shape

In [3]:
mX = np.mean(X, axis = 0) 
A = X - mX
C = np.dot(A.T, A)
#C = np.dot(A.T, A)/(m-1) #sample covariance, np.cov(X.T, ddof=1)
C.shape

(10, 10)

In [4]:
np.linalg.matrix_rank(A), np.linalg.matrix_rank(C)

(4, 4)

In [5]:
w, V = linalg.eigh(C) # C is symmetric
# decending order by reverse
w = w[::-1] 
V = V[:, ::-1]
V.shape

(10, 10)

In [6]:
np.round(w,2)

array([3600.43, 2144.32, 1316.3 ,  878.14,    0.  ,    0.  ,    0.  ,
         -0.  ,   -0.  ,   -0.  ])

In [7]:
# PCA projection using k-PC
k = 3
A = X - mX
Yk = np.dot(A, V[:, :k] )
np.round(Yk,2)

array([[-16.35, -28.74,   9.22],
       [-34.27,   7.41, -23.45],
       [ -1.65,  -3.34,  18.62],
       [  6.25,  34.11,  10.55],
       [ 46.01,  -9.44, -14.95]])

In [8]:
# Approximation by back projection using k-PC

Y = np.dot(A, V) # PCA projection

k = 3
w[w<0] = 0 # w> 0 but numerically, it will be < 0
ratio = np.sum(w[:k])/np.sum(w)
print("Approximation:{}%".format(ratio*100))

Vk = V.copy()
Vk[:, k:] = 0
Xk = np.dot(Y, Vk.T) + mX
np.round(Xk, 1)

Approximation:88.93916572364614%


array([[32.5, 26.1, 41.1, 36.3,  7.9,  2.4, 50.7, 27.4, 37.4, 27.7],
       [30.2, 42. , 20.6, 36.6, 17. , 42.2, 48.1, 26.5, 24.9, 14.1],
       [33.4, 29.3, 43.5, 26.4, 14.8,  4.8, 29.2, 16.2, 41.9, 14.5],
       [32.2, 37.2, 34.9, 16.7, 24.5, 24.5,  8.1,  5.8, 40.4, -1.5],
       [15.7,  0.4, 14.9,  5.1, 10.7,  9. ,  7.9, 12.1, 43.4, 37.2]])

In [9]:
error = np.sqrt(np.sum((X - Xk)**2)) # Frobenius Norm
error

29.633456681060427